services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=social
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 3031:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
