packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0

  next: ^15.1.3

  tailwindcss: ^4.0.0
  "@tailwindcss/postcss": ^4.0.0
  "@tailwindcss/vite": ^4.0.0
  tailwind-merge: ^3.0.1
  postcss: ^8.4.47

  storybook: ^8.5.8
  "@storybook/addon-essentials": ^8.5.8
  "@storybook/addon-interactions": ^8.5.8
  "@storybook/addon-links": ^8.5.8
  "@storybook/addon-themes": ^8.5.8
  "@storybook/nextjs": ^8.5.8
  "@storybook/react": ^8.5.8
  "@storybook/react-vite": ^8.5.8
  "@storybook/test": ^8.5.8

  tsup: ^8.3.6

  vite: ^6.1.1
  "@vitejs/plugin-react": ^4.3.4
  vitest: ^3.0.6
  vite-plugin-dts: ^4.5.0
  playwright: ^1.49.1
  "@playwright/test": ^1.49.1
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  jsdom: ^25.0.1

  "@types/node": ^22.10.5
