packages:
  - "apps/*"
  - "packages/*"
  - "system/*"

publicHoistPattern:
  - '@storybook/*'

catalog:
  "@effector/next": ^0.7.1
  "@effector/swc-plugin": 0.8.0-swc1.12.0
  "@next/env": ^15.4.6
  "@playwright/test": ^1.49.1
  "@storybook/addon-essentials": ^8.6.12
  "@storybook/addon-interactions": ^8.6.12
  "@storybook/addon-links": ^8.6.12
  "@storybook/addon-themes": ^8.6.12
  "@storybook/nextjs": ^8.6.12
  "@storybook/react": ^8.6.12
  "@storybook/react-vite": ^8.6.12
  "@storybook/test": ^8.6.12
  "@tailwindcss/postcss": ^4.1.0
  "@tailwindcss/vite": ^4.1.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  "@types/node": ^22.10.5
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@types/react-is": ^19.0.0
  "@vitejs/plugin-react": ^4.3.4
  "@withease/factories": ^1.0.5
  client-only: ^0.0.1
  effector-react: ^23.3.0
  effector-storage: ^7.1.0
  effector: ^23.3.0
  jsdom: ^25.0.1
  nanoid: ^5.1.5
  next: ^15.4.6
  patronum: ^2.3.0
  postcss: ^8.4.47
  react-dom: ^19.0.0
  react-is: ^19.0.0
  react: ^19.0.0
  server-only: ^0.0.1
  storybook: ^8.6.12
  tailwind-merge: ^3.0.2
  tailwindcss: ^4.1.0
  tsup: ^8.5.0
  tw-animate-css: ^1.2.4
  typescript: ^5.7.2
  use-sync-external-store: ^1.4.0
  vite-plugin-dts: ^4.5.0
  vite: ^6.0.9
  vitest: ^3.0.6
  zod: ^3.24.2
