packages:
  - apps/*
  - packages/*
  - system/*

catalog:
  "@effector/next": ^0.7.1
  "@effector/swc-plugin": 0.8.0-swc1.12.0
  "@next/env": ^15.4.6
  "@playwright/test": ^1.49.1
  "@storybook/addon-links": ^9.1.2
  "@storybook/addon-themes": ^9.1.2
  "@storybook/nextjs": ^9.1.2
  "@storybook/react-vite": ^9.1.2
  "@tailwindcss/postcss": ^4.1.11
  "@tailwindcss/vite": ^4.1.11
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  "@types/node": ^24.2.1
  "@types/react": ^19.1.10
  "@types/react-dom": ^19.1.7
  "@types/react-is": ^19.0.0
  "@vitejs/plugin-react": ^5.0.0
  "@withease/factories": ^1.0.5
  client-only: ^0.0.1
  effector-react: ^23.3.0
  effector-storage: ^7.1.0
  effector: ^23.3.0
  jsdom: ^26.1.0
  nanoid: ^5.1.5
  next: ^15.4.6
  patronum: ^2.3.0
  postcss: ^8.4.47
  react-dom: ^19.1.1
  react-is: ^19.1.1
  react: ^19.1.1
  server-only: ^0.0.1
  storybook: ^9.1.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tsup: ^8.5.0
  tw-animate-css: ^1.2.4
  typescript: ^5.9.2
  use-sync-external-store: ^1.4.0
  vite-plugin-dts: ^4.5.4
  vite: ^7.1.2
  vitest: ^3.2.4
  zod: ^3.24.2
