packages:
  - "apps/*"
  - "packages/*"
  - "system/*"

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  use-sync-external-store: ^1.4.0
  server-only: ^0.0.1
  client-only: ^0.0.1

  effector: ^23.3.0
  effector-react: ^23.3.0
  "@effector/next": ^0.7.0
  "@effector/swc-plugin": 0.7.0-swc1.11.0
  effector-storage: ^7.1.0
  patronum: ^2.3.0
  "@withease/factories": ^1.0.5

  next: ^15.2.3
  "@next/env": ^15.2.3

  tailwindcss: 4.0.9
  "@tailwindcss/postcss": 4.0.9
  "@tailwindcss/vite": 4.0.9
  tailwind-merge: ^3.0.2
  postcss: ^8.4.47

  storybook: ^8.6.0
  "@storybook/addon-essentials": ^8.6.0
  "@storybook/addon-interactions": ^8.6.0
  "@storybook/addon-links": ^8.6.0
  "@storybook/addon-themes": ^8.6.0
  "@storybook/nextjs": ^8.6.0
  "@storybook/react": ^8.6.0
  "@storybook/react-vite": ^8.6.0
  "@storybook/test": ^8.6.0

  tsup: ^8.3.6

  vite: ^6.0.9
  "@vitejs/plugin-react": ^4.3.4
  vitest: ^3.0.6
  vite-plugin-dts: ^4.5.0
  playwright: ^1.49.1
  "@playwright/test": ^1.49.1
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  jsdom: ^25.0.1

  "@types/node": ^22.10.5

  concurrently: ^9.1.2

  zod: ^3.24.2
