packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0

  next: ^15.1.3

  tailwindcss: ^3.4.7
  autoprefixer: ^10.4.20
  postcss: ^8.4.47
  postcss-import: ^16.1.0
  "@types/postcss-import": ^14.0.3

  storybook: ^8.4.7
  "@storybook/addon-essentials": ^8.4.7
  "@storybook/addon-interactions": ^8.4.7
  "@storybook/addon-links": ^8.4.7
  "@storybook/addon-themes": ^8.4.7
  "@storybook/react": ^8.4.7
  "@storybook/react-vite": ^8.4.7
  "@storybook/test": ^8.4.7

  vite: ^5.3.5
  "@vitejs/plugin-react": ^4.3.4
  vitest: ^2.1.8
  playwright: ^1.49.1
  "@playwright/test": ^1.49.1
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  jsdom: ^25.0.1
