export { SynthParam, synthParamType } from './synth-param'
export { AutomationCurve } from './automation-curve'
export { ScalarSynthParam } from './scalar-synth-param'
export { EnumSynthParam } from './enum-synth-param'
export { AudioSynthParam } from './audio-synth-param'
