name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install root dependencies
        run: pnpm install

      - name: Run Biome
        run: pnpm run ci:check

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - packages/common
          - packages/ui-kit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install root dependencies
        run: pnpm install

      - name: Install ${{ matrix.package }} dependencies
        working-directory: ${{ matrix.package }}
        run: pnpm install

      - name: Run unit tests
        working-directory: ${{ matrix.package }}
        run: pnpm run test:unit

  screen-test:
    name: Screen tests
    runs-on: macos-latest

    strategy:
      matrix:
        package:
          - packages/ui-kit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install root dependencies
        run: pnpm install

      - name: Install ${{ matrix.package }} dependencies
        working-directory: ${{ matrix.package }}
        run: pnpm install

      - name: Install playwright browsers
        working-directory: ${{ matrix.package }}
        run: pnpm run playwright:install

      - name: Run screen tests
        working-directory: ${{ matrix.package }}
        run: pnpm run test:screen

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ${{ matrix.package }}/playwright-report/
          retention-days: 30
